# Generated by Django 5.0.2 on 2024-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_id_projectr_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
