# Generated by Django 5.0.3 on 2024-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_descripcion_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='task',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
