# Generated by Django 5.0.3 on 2024-03-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_complete_task_date_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
