# Generated by Django 5.0.2 on 2024-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_id_user_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_complet',
            field=models.DateTimeField(null=True),
        ),
    ]
