# Generated by Django 5.0.2 on 2024-02-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_date_complet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_complet',
            new_name='date_complete',
        ),
    ]
