# Generated by Django 5.0.3 on 2024-03-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_date_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
